blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/collabits-platform/collabits/discussions/category_choices
    about: Ask questions and discuss with other community members.
